version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/amos-dev
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
     - location: deployment-scripts/app-stop.sh
       timeout: 10
       runas: ubuntu
  BeforeInstall:
    - location: deployment-scripts/before-install.sh
      timeout: 10
      runas: ubuntu
  AfterInstall:
    - location: deployment-scripts/after-install.sh
      timeout: 100
      runas: ubuntu
  ApplicationStart:
    - location: deployment-scripts/app-start.sh
      timeout: 10
      runas: ubuntu
  ValidateService:
    - location: deployment-scripts/validate-service.sh
      timeout: 40
      runas: ubuntu
